const colors = {
  light: {
    text: "#0D0D0D",
    tint: "#E84C1E",
    background: "#FFFFFF",
    foreground: "#0D0D0D",
    card: "#F8F8F8",
    cardForeground: "#0D0D0D",
    primary: "#E84C1E",
    primaryForeground: "#FFFFFF",
    secondary: "#FFF4F0",
    secondaryForeground: "#0D0D0D",
    muted: "#F4F4F4",
    mutedForeground: "#8A8A8A",
    accent: "#C8860A",
    accentForeground: "#FFFFFF",
    destructive: "#DC2626",
    destructiveForeground: "#FFFFFF",
    border: "#EBEBEB",
    input: "#EBEBEB",
    surface: "#FFFFFF",
    surfaceElevated: "#FFFFFF",
    gold: "#C8860A",
    goldLight: "#F5E8C0",
    fire: "#E84C1E",
    fireDark: "#B83310",
    navy: "#0F1B2D",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#E84C1E",
    background: "#0A0A0A",
    foreground: "#FFFFFF",
    card: "#141414",
    cardForeground: "#FFFFFF",
    primary: "#E84C1E",
    primaryForeground: "#FFFFFF",
    secondary: "#1A1A1A",
    secondaryForeground: "#FFFFFF",
    muted: "#1A1A1A",
    mutedForeground: "#666666",
    accent: "#F5A623",
    accentForeground: "#0A0A0A",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E1E1E",
    input: "#1E1E1E",
    surface: "#141414",
    surfaceElevated: "#1E1E1E",
    gold: "#F5A623",
    goldLight: "#2A2215",
    fire: "#E84C1E",
    fireDark: "#B83310",
    navy: "#0F1B2D",
  },
  radius: 12,
};

export default colors;
