const colors = {
  light: {
    text: "#0B1F4E",
    tint: "#0B2A7A",
    background: "#FFFFFF",
    foreground: "#0B1F4E",
    card: "#F8F9FF",
    cardForeground: "#0B1F4E",
    primary: "#0B2A7A",
    primaryForeground: "#FFFFFF",
    secondary: "#FFF3ED",
    secondaryForeground: "#C04B00",
    muted: "#F3F4F8",
    mutedForeground: "#6B7280",
    accent: "#E05A1F",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E5E7EB",
    input: "#E5E7EB",
    gold: "#F59E0B",
  },
  dark: {
    text: "#F0F4FF",
    tint: "#5B8DEF",
    background: "#080F1E",
    foreground: "#F0F4FF",
    card: "#101C35",
    cardForeground: "#F0F4FF",
    primary: "#3B6FE0",
    primaryForeground: "#FFFFFF",
    secondary: "#1A1206",
    secondaryForeground: "#FF8C42",
    muted: "#151F38",
    mutedForeground: "#8A94A8",
    accent: "#E05A1F",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E2A45",
    input: "#1E2A45",
    gold: "#F59E0B",
  },
  radius: 12,
};

export default colors;
